-- 初始化数据库
-- 栏目分类
INSERT INTO `zbp_category` ( `cate_Name`, `cate_Order`, `cate_Type`, `cate_Count`, `cate_Alias`, `cate_Group`, `cate_Intro`, `cate_RootID`, `cate_ParentID`, `cate_CreateTime`, `cate_PostTime`, `cate_UpdateTime`, `cate_Template`, `cate_LogTemplate`, `cate_Meta`) VALUES ( '未分类', 0, 0, 1, 'uncategorized', '', '', 0, 0, NOW(), 0, NOW(), '', '', '');
INSERT INTO `zbp_category` ( `cate_Name`, `cate_Order`, `cate_Type`, `cate_Count`, `cate_Alias`, `cate_Group`, `cate_Intro`, `cate_RootID`, `cate_ParentID`, `cate_CreateTime`, `cate_PostTime`, `cate_UpdateTime`, `cate_Template`, `cate_LogTemplate`, `cate_Meta`) VALUES ( '星座', 0, 0, 0, '', '', '', 0, 0, NOW(), 0, NOW(), '', '', '');
INSERT INTO `zbp_category` ( `cate_Name`, `cate_Order`, `cate_Type`, `cate_Count`, `cate_Alias`, `cate_Group`, `cate_Intro`, `cate_RootID`, `cate_ParentID`, `cate_CreateTime`, `cate_PostTime`, `cate_UpdateTime`, `cate_Template`, `cate_LogTemplate`, `cate_Meta`) VALUES ( '美食', 0, 0, 0, '', '', '', 0, 0, NOW(), 0, NOW(), '', '', '');
INSERT INTO `zbp_category` ( `cate_Name`, `cate_Order`, `cate_Type`, `cate_Count`, `cate_Alias`, `cate_Group`, `cate_Intro`, `cate_RootID`, `cate_ParentID`, `cate_CreateTime`, `cate_PostTime`, `cate_UpdateTime`, `cate_Template`, `cate_LogTemplate`, `cate_Meta`) VALUES ( '旅游', 0, 0, 0, '', '', '', 0, 0, NOW(), 0, NOW(), '', '', '');
INSERT INTO `zbp_category` ( `cate_Name`, `cate_Order`, `cate_Type`, `cate_Count`, `cate_Alias`, `cate_Group`, `cate_Intro`, `cate_RootID`, `cate_ParentID`, `cate_CreateTime`, `cate_PostTime`, `cate_UpdateTime`, `cate_Template`, `cate_LogTemplate`, `cate_Meta`) VALUES ( '生活', 0, 0, 0, '', '', '', 0, 0, NOW(), 0, NOW(), '', '', '');
INSERT INTO `zbp_category` ( `cate_Name`, `cate_Order`, `cate_Type`, `cate_Count`, `cate_Alias`, `cate_Group`, `cate_Intro`, `cate_RootID`, `cate_ParentID`, `cate_CreateTime`, `cate_PostTime`, `cate_UpdateTime`, `cate_Template`, `cate_LogTemplate`, `cate_Meta`) VALUES ( '健康', 0, 0, 0, '', '', '', 0, 0, NOW(), 0, NOW(), '', '', '');
INSERT INTO `zbp_category` ( `cate_Name`, `cate_Order`, `cate_Type`, `cate_Count`, `cate_Alias`, `cate_Group`, `cate_Intro`, `cate_RootID`, `cate_ParentID`, `cate_CreateTime`, `cate_PostTime`, `cate_UpdateTime`, `cate_Template`, `cate_LogTemplate`, `cate_Meta`) VALUES ( '教育', 0, 0, 0, '', '', '', 0, 0, NOW(), 0, NOW(), '', '', '');
INSERT INTO `zbp_category` ( `cate_Name`, `cate_Order`, `cate_Type`, `cate_Count`, `cate_Alias`, `cate_Group`, `cate_Intro`, `cate_RootID`, `cate_ParentID`, `cate_CreateTime`, `cate_PostTime`, `cate_UpdateTime`, `cate_Template`, `cate_LogTemplate`, `cate_Meta`) VALUES ( '宠物', 0, 0, 0, '', '', '', 0, 0, NOW(), 0, NOW(), '', '', '');
INSERT INTO `zbp_category` ( `cate_Name`, `cate_Order`, `cate_Type`, `cate_Count`, `cate_Alias`, `cate_Group`, `cate_Intro`, `cate_RootID`, `cate_ParentID`, `cate_CreateTime`, `cate_PostTime`, `cate_UpdateTime`, `cate_Template`, `cate_LogTemplate`, `cate_Meta`) VALUES ( '母婴', 0, 0, 0, '', '', '', 0, 0, NOW(), 0, NOW(), '', '', '');
INSERT INTO `zbp_category` ( `cate_Name`, `cate_Order`, `cate_Type`, `cate_Count`, `cate_Alias`, `cate_Group`, `cate_Intro`, `cate_RootID`, `cate_ParentID`, `cate_CreateTime`, `cate_PostTime`, `cate_UpdateTime`, `cate_Template`, `cate_LogTemplate`, `cate_Meta`) VALUES ( '科普', 0, 0, 0, '', '', '', 0, 0, NOW(), 0, NOW(), '', '', '');
INSERT INTO `zbp_category` ( `cate_Name`, `cate_Order`, `cate_Type`, `cate_Count`, `cate_Alias`, `cate_Group`, `cate_Intro`, `cate_RootID`, `cate_ParentID`, `cate_CreateTime`, `cate_PostTime`, `cate_UpdateTime`, `cate_Template`, `cate_LogTemplate`, `cate_Meta`) VALUES ( '数码', 0, 0, 0, '', '', '', 0, 0, NOW(), 0, NOW(), '', '', '');
INSERT INTO `zbp_category` ( `cate_Name`, `cate_Order`, `cate_Type`, `cate_Count`, `cate_Alias`, `cate_Group`, `cate_Intro`, `cate_RootID`, `cate_ParentID`, `cate_CreateTime`, `cate_PostTime`, `cate_UpdateTime`, `cate_Template`, `cate_LogTemplate`, `cate_Meta`) VALUES ( '植物', 0, 0, 0, '', '', '', 0, 0, NOW(), 0, NOW(), '', '', '');
INSERT INTO `zbp_category` ( `cate_Name`, `cate_Order`, `cate_Type`, `cate_Count`, `cate_Alias`, `cate_Group`, `cate_Intro`, `cate_RootID`, `cate_ParentID`, `cate_CreateTime`, `cate_PostTime`, `cate_UpdateTime`, `cate_Template`, `cate_LogTemplate`, `cate_Meta`) VALUES ( '排行榜', 0, 0, 0, '', '', '', 0, 0, NOW(), 0, NOW(), '', '', '');
INSERT INTO `zbp_category` ( `cate_Name`, `cate_Order`, `cate_Type`, `cate_Count`, `cate_Alias`, `cate_Group`, `cate_Intro`, `cate_RootID`, `cate_ParentID`, `cate_CreateTime`, `cate_PostTime`, `cate_UpdateTime`, `cate_Template`, `cate_LogTemplate`, `cate_Meta`) VALUES ( '影视', 0, 0, 0, '', '', '', 0, 0, NOW(), 0, NOW(), '', '', '');